#!/bin/bash

# ============================================
# FILE: scripts/setup-tls.sh
# ============================================
# Generate TLS certificates for Kubernetes deployment
# Usage: ./setup-tls.sh [domain-name]
# Save this as: scripts/setup-tls.sh
# Make executable: chmod +x scripts/setup-tls.sh
# ============================================

setup_tls() {
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

DOMAIN=${1:-"jideka.com.ng"}
TLS_DIR="./tls"
K8S_DIR="./k8s"

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  TLS Certificate Setup for Kubernetes${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

if ! command -v mkcert &> /dev/null; then
    echo -e "${RED}Error: mkcert is not installed${NC}"
    echo ""
    echo "Install mkcert:"
    echo "  Mac:   brew install mkcert"
    echo "  Linux: See https://github.com/FiloSottile/mkcert#installation"
    echo ""
    exit 1
fi

echo -e "${YELLOW}Domain:${NC} $DOMAIN"
echo ""

mkdir -p "$TLS_DIR"
cd "$TLS_DIR"

echo -e "${YELLOW}Step 1:${NC} Checking mkcert Certificate Authority..."
if ! mkcert -CAROOT &> /dev/null; then
    echo -e "${YELLOW}Installing mkcert CA...${NC}"
    mkcert -install
    echo -e "${GREEN}✓ mkcert CA installed${NC}"
else
    echo -e "${GREEN}✓ mkcert CA already installed${NC}"
fi
echo ""

echo -e "${YELLOW}Step 2:${NC} Generating TLS certificates for $DOMAIN..."
if [ -f "${DOMAIN}.pem" ] && [ -f "${DOMAIN}-key.pem" ]; then
    echo -e "${YELLOW}Certificates already exist. Regenerating...${NC}"
    rm -f "${DOMAIN}.pem" "${DOMAIN}-key.pem"
fi

mkcert "$DOMAIN"

if [ ! -f "${DOMAIN}.pem" ] || [ ! -f "${DOMAIN}-key.pem" ]; then
    echo -e "${RED}Error: Failed to generate certificates${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Certificates generated:${NC}"
echo "  - ${DOMAIN}.pem (certificate)"
echo "  - ${DOMAIN}-key.pem (private key)"
echo ""

echo -e "${YELLOW}Step 3:${NC} Encoding certificates to base64..."
cat "${DOMAIN}.pem" | base64 | tr -d '\n' > tls.crt.base64
echo -e "${GREEN}✓ Certificate encoded${NC}"

cat "${DOMAIN}-key.pem" | base64 | tr -d '\n' > tls.key.base64
echo -e "${GREEN}✓ Private key encoded${NC}"
echo ""

echo -e "${YELLOW}Step 4:${NC} Creating Kubernetes TLS Secret YAML..."

cd ..
cat > "$K8S_DIR/04-tls-secret.yaml" << EOF
# Auto-generated by setup-tls.sh
# Date: $(date)
# Domain: $DOMAIN

apiVersion: v1
kind: Secret
metadata:
  name: user-app-tls-secret
  namespace: user-app
type: kubernetes.io/tls
data:
  tls.crt: $(cat "$TLS_DIR/tls.crt.base64")
  tls.key: $(cat "$TLS_DIR/tls.key.base64")
EOF

echo -e "${GREEN}✓ TLS Secret YAML created: $K8S_DIR/04-tls-secret.yaml${NC}"
echo ""

echo -e "${YELLOW}Step 5:${NC} Verifying TLS Secret..."
CERT_SIZE=$(wc -c < "$TLS_DIR/tls.crt.base64" | tr -d ' ')
KEY_SIZE=$(wc -c < "$TLS_DIR/tls.key.base64" | tr -d ' ')

if [ "$CERT_SIZE" -lt 100 ] || [ "$KEY_SIZE" -lt 100 ]; then
    echo -e "${RED}Error: Certificate or key seems too small${NC}"
    echo "Certificate size: $CERT_SIZE bytes"
    echo "Key size: $KEY_SIZE bytes"
    exit 1
fi

echo -e "${GREEN}✓ TLS Secret verified${NC}"
echo "  Certificate size: $CERT_SIZE bytes"
echo "  Key size: $KEY_SIZE bytes"
echo ""

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Next steps:"
echo ""
echo "1. Update your /etc/hosts file:"
echo -e "   ${YELLOW}sudo nano /etc/hosts${NC}"
echo "   Add this line (replace <MINIKUBE-IP> with actual IP):"
echo -e "   ${YELLOW}<MINIKUBE-IP> $DOMAIN${NC}"
echo ""
echo "2. Deploy the TLS secret to Kubernetes:"
echo -e "   ${YELLOW}kubectl apply -f $K8S_DIR/04-tls-secret.yaml${NC}"
echo ""
echo "3. Verify the secret:"
echo -e "   ${YELLOW}kubectl get secret user-app-tls-secret -n user-app${NC}"
echo ""
echo "4. Access your application:"
echo -e "   ${YELLOW}https://$DOMAIN${NC}"
echo ""

echo "Certificate Details:"
echo "===================="
openssl x509 -in "$TLS_DIR/${DOMAIN}.pem" -text -noout | grep -A2 "Subject:"
echo ""
openssl x509 -in "$TLS_DIR/${DOMAIN}.pem" -text -noout | grep -A2 "Validity"
echo ""

echo -e "${GREEN}TLS setup completed successfully!${NC}"
}